[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lk_math = "0.2.0"
ndarray = "0.15.6"

# [build]
# target = ["x86_64-pc-windows-msvc"]
