[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.23.1"
nalgebra = "0.31.4"

# [build]
# target = ["x86_64-pc-windows-msvc"]